### ISSUE TITLE
Inner Exception : AADSTS90014

### ISSUE THREAD

**Issue by knstntndmdnkv** [tamhinsf/ucwa-sfbo-console#1]
Hello.

Getting the following exception.
![inner exception aadsts90014](https://cloud.githubusercontent.com/assets/2073188/16545090/5613a19a-4127-11e6-848b-33b8202815b5.jpg)

Of course, I've checked tenant, clientID and credentials.

**Comment by knstntndmdnkv** [comment]
Seems to be it was wrong application type on Azure.

**Comment by tamhinsf** [comment]
Yeah - my code only supports native apps at this time.  I'll get around to web-based ones at some point.
