### ISSUE TITLE
Is it possible to add contacts via UCWA SFBO?

### ISSUE THREAD

**Issue by knstntndmdnkv** [tamhinsf/ucwa-sfbo-console#2]
Hello.

I wonder, whether it is possible or not to add new contact to contacts list or accept "contact request" by using UCWA SFBO? API documentation describes myContacts as read-only but may be it is possible to add contacts somehow?

**Comment by knstntndmdnkv** [comment]
Here we have statement about adding contacts in UCWA 2.0 https://msdn.microsoft.com/en-us/skype/ucwa/whatsnewinucwa2_0

> UCWA 2.0 now supports the ability to add and remove Contacts, User Groups, as well as Distribution Groups from the contact list.

So, it seems to be it is possible to do somehow.

**Comment by tamhinsf** [comment]
Hey there - as you've probably noticed, specific details on how to add contacts is rather sparse.  I'll take this up as an enhancement for now and see what's possible.

**Comment by knstntndmdnkv** [comment]
Hey there, thanks, it would be really great enhancement if you clear it up.

**Comment by tamhinsf** [comment]
Added to the latest update.   Check out UcwaMyGroupMemberships.cs to see how it's done and Program.cs to see how it's called.
