### ISSUE TITLE
User without admin access cannot login

### ISSUE THREAD

**Issue by pavanrachapudy** [tamhinsf/ucwa-sfbo-console#3]
As suggested, when I created my app by logging in as user and started running the app. I choose the option of having login through console(hard coded username and password). When I do this it gives me an error. "AADSTS65001: The user or administrator has not consented to use the application with ID. Send an interactive authorization request for this user and resource". I tried doing it from dialog box. It says "AADSTS90093: Calling principal cannot consent due to lack of permissions.". Am I missing something? How can this be achieved without global administrator doing it?

**Comment by tamhinsf** [comment]
Hi there - sorry, I didn't notice your message until now.   The UCWA APIs for Skype for Business Online require admin consent, and it looks like I'm missing this bit of instruction in my docs:

https://msdn.microsoft.com/en-us/skype/ucwa/developingucwaapplicationsforsfbonline

I'll update the README.md to reflect this with the instructions here, and then close this issue.

https://msdn.microsoft.com/en-us/skype/websdk/docs/developwebsdkappsforsfbonline#tenant-administrator-consent-flow

**Comment by ankitabhishek93** [comment]
Hi,
I am having some issue in creating "IM" using your code.If you have any repository about it do let me know or any leads on that particular scenario.

**Comment by tamhinsf** [comment]
Updated docs for admin consent
