### ISSUE TITLE
unable to create IM invitation

### ISSUE THREAD

**Issue by ankitabhishek93** [tamhinsf/ucwa-sfbo-console#4]
Hi,
I am having some issue in creating "IM" using your code.If you have any repository about it do let me know or any leads on that particular scenario.

**Comment by tamhinsf** [comment]
I added some missing instructions to README.md - you need to make sure to perform admin consent to the Azure AD tenant where you've registered your UCWA app.  

Aside from that, I'd suggest you take a look at the flow that'd documented here:

https://msdn.microsoft.com/en-us/skype/ucwa/sendanim

**Comment by ankitabhishek93** [comment]
I am unable to get a URI GET https://lyncweb.contoso.com/ucwa/oauth/v1/applications/102/events?ack=2 HTTP/1.1 instead of that I am getting GET https://lyncweb.contoso.com/ucwa/oauth/v1/applications/102/events?ack=1 HTTP/1.1
How to get that event handle for the conversation as I am able to ping the person.If possible can you share some code snippet for the same.
