### ISSUE TITLE
The request body must contain the following parameter: 'client_secret or client_assertion'

### ISSUE THREAD

**Issue by aherrick** [tamhinsf/ucwa-sfbo-console#8]
Receive this error when trying the sample. Spent some time debugging and am able to get an access token after creating like this:

```
                    ClientCredential credentials = new ClientCredential(clientId, clientSecret);
                    authenticationResult = authContext.AcquireTokenAsync(resourceHostUri, credentials).Result;
```
However wasn't able to get much further. What more do we need to get this sample updated/working?

**Comment by tamhinsf** [comment]
Hey - sorry for just only noticing this.  Did you register your app as a native application or a web app?  Which method are you using to authenticate (console, dialog, code)?

I've downloaded and re-built my app - didn't run into any issues.

**Comment by tamhinsf** [comment]
Hi - closing this issue as I haven't had an update.  Please go ahead and re-open if you're still having issues.

**Comment by aherrick** [comment]
I believe it was Web and you required Native. No worries as I figured it out using the raw Graph calls. Thanks!
